### ISSUE TITLE
The scheduled tasks have not run for more than 10 minutes

### ISSUE THREAD

**Issue by csaeum** [FriendsOfShopware/FroshTools#97]
### Question

I wanted to ask what could be wrong with the planned tasks.
I've searched everything and checked the CronJobs several times.
But don't find the error. Could it be that you have made a mistake here?
How can I proceed to find out where it hangs?

![grafik](https://user-images.githubusercontent.com/1543510/180603148-073d91a7-d91f-4649-8112-2ecebf4c1f22.png)

**Comment by tinect** [comment]
Check the tab "Scheduled Tasks Manager" that every status is at `scheduled` and the next executation time should be in future. otherwise it might just hang around :-)

**Comment by Isengo1989** [comment]
@csaeum mostly this happens when a big product export or smth else blocks your queue. Afaik RabbitMQ is like most/all MQ a first in first out. 

Product Export Message is pushed to the queue at noon but beforehand there was an export with 1000 messages this can easily block your execution for + 10 minutes.

It would be nice to configure this in the plugin config by the way :smile: 

Best way to handle this longterm is to have 2 or more queues. One for high priority messages like scheduled tasks and one for example for indexing etc.

**Comment by csaeum** [comment]
Thank you for your help!!
I have 47 products, each with different variants, tw 10 tw 60.
The preview of the GS template generated in about 3 seconds and then has about 2800 lines which should be about 1250 articles.

It could just be these exports!

So the tasks planned according to the page all run smoothly:

I'm just at a loss to find where it hacks.
![grafik](https://user-images.githubusercontent.com/1543510/185488526-d8cc6602-d134-4ec6-bea3-f3e9307a54cf.png)

**Comment by Isengo1989** [comment]
@csaeum indeed the screenshot looks fine to me. Nothing is queued and all are scheduled and in the future :man_shrugging:

**Comment by tinect** [comment]
Is there any open issue, or can we close?
